services:
  go:
    build:
      context: .
      dockerfile: build/go/Dockerfile
    container_name: go
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
  db:
    container_name: postgres
    build:
      context: .
      dockerfile: build/postgresql/Dockerfile
    ports:
      - "5432:5432"
    # set shared memory limit when using build-compose
    shm_size: 128mb
    volumes:
      - ./build/postgresql/data:/var/lib/postgresql/data
      - ./build/postgresql/init:/build-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "Asia/Tokyo"
      PGDATA: /var/lib/postgresql/data/pgdata